### ISSUE TITLE
Chapter 2

### ISSUE THREAD

**Issue by v9w58fe7zt0i** [oetiker/lshort#10]
Please consider editing Chapter 2 for clarity and punctuation. The English syntax is awkward and unclear.

Examples:
Confusing: 2.2.2 uses the word "hyphenation" in the argument for the _hyphenation_ command. Please don't ever show an example that uses the same word as a command and as an argument. It introduces unnecessary confusion.

Awkward English: 2.4.3 _A character often seen in web addresses is the tilde.  To generate this in
LATEX use \~{} but the result ( ̃) is not really what you want.  Try this instead:_

Awkward English: 2.4.4  _But normal ‘/’ character may be still used for ratios or units, e.g. 5 MB/s._
(also, the author doesn't explain why ratios and units may be treated differently)

**Comment by McSinyx** [comment]
I think PRs will be gladly excepted.
