### ISSUE TITLE
The word Käse in Table 4.1 of Version 6.3

### ISSUE THREAD

**Issue by billyandriam** [oetiker/lshort#13]
On the Version 6.3 of the document, the section 4.2 tackles the introduction to Indexing.
Referring to the Table 4.1 on the page 75, there is the following entry:

>`\index{Kaese@K\''ase}` &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Käse**, 33&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Formatted entry

I would like to ask if the word **Käse** should not be in bold.

**Comment by oetiker** [comment]
it should :) fixed
