### ISSUE TITLE
RFE: readbility on a smartphone/tablet

### ISSUE THREAD

**Issue by atrent** [oetiker/lshort#19]
I know that it may not sound very useful but I'd like to read it on my phone/tablet, the current setup generates a pdf unreadable on a small screen so I've tried something like:
```
\documentclass[12pt]{extbook}
\usepackage{mylayout}
\usepackage[paperheight=20cm,paperwidth=10cm,inner=1.2cm,outer=1.2cm,bottom=1.5cm,top=1.5cm]{geometry}
\input{preamble}
\input{title}
\input{lshort-base}
```
in the main file and the resulting pdf is readable on the phone (6'' display) but the 'example' environment is too cramped in the page...
I'm not that expert in \LaTeX to propose a patch to the environment, do you think it could be rewritten in a more "adaptive" way?
Maybe sensing the width of the page and resorting to a sequential layout instead of the side-by-side?
Thank you

**Comment by atrent** [comment]
I've understood the structure of the files, what I'm not able to do is to edit the definition:
`\newenvironment{example}`
in the 'lshort.sty' file, I'm not that confident in \LaTeX syntax

**Comment by oetiker** [comment]
all the code has been redone in latex3 syntax by @marcin-serwin. looks pretty neat now!
