### ISSUE TITLE
Use GitHub Actions to build pdfs

### ISSUE THREAD

**Issue by FranklinChen** [oetiker/lshort#38]
I'm currently having problems building the pdfs with `make all`, as LaTeX is going into an infinite loop. (This was not the case several days ago.) So it would probably be a good idea to use GitHub Actions to test building the pdfs and ensure a reproducible build.

**Comment by oetiker** [comment]
the new stuff only works if you have a current texlive (2022) installed ...  but yes github actions is a good idea ... will look into it

**Comment by FranklinChen** [comment]
I do have texlive 2022 installed.

It turns out I wasn't patient enough. The build took a very long time and I initially misinterpreted some output as indicating an infinite loop of failure but I was wrong. The build works.

**Comment by marcin-serwin** [comment]
The first build is now much longer because some examples are standalone PDFs, so LaTeX is started several times to produce them. These PDFs are cached so subsequent build should be much faster.
