### ISSUE TITLE
Please add a copy of GPLv2

### ISSUE THREAD

**Issue by McSinyx** [oetiker/lshort#4]
As noted in `book/src/contrib.tex`'s header:

> You should have received a copy of the GNU General Public License
> along with this document; if not, write to the Free Software
> Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

Also, this will make Github display the book as GPLed and interest free software enthusiasts into looking further.

In addition, could you please edit the README in `book` and move it to the root directory to briefly describe the content of this repository?

**Comment by oetiker** [comment]
fixed via aecb14a91ff28fd9fcdb630bfe08855f1c9c144c
