### ISSUE TITLE
Usage of `\flushleft`

### ISSUE THREAD

**Issue by eg9** [oetiker/lshort#7]
Using `\flushleft` in the wild is very bad practice, because it starts a `\trivlist` that's never finished:

```latex
> latexdef flushleft

\flushleft:
macro:->\trivlist \raggedright \item \relax 
```

The command to be used is, instead, `\raggedright`.

Referring to version 6.2, `\flushleft` appears twice, on page 32 and 119. In my opinion it should be removed altogether, because it (or, better, `\raggedright`) is only aimed to not having underfull/overfull boxes in the typeset example.

Newbies might think that `\flushleft` is an essential part of the code, see https://tex.stackexchange.com/q/438659/4427 for an example.

**Comment by oetiker** [comment]
cool! thanks ... would you like to create a PR ?

**Comment by eg9** [comment]
@oetiker I'd rather not do it. My command of Git is inexistent.
