### ISSUE TITLE
Usage of "e.g."

### ISSUE THREAD

**Issue by v9w58fe7zt0i** [oetiker/lshort#8]
Please consider using _for example_ instead of _e.g._
Example: You will learn in the following sections how to force line breaks with e.g. \\\\ ...
This is awkward and unclear (and missing 2 commas).

Better: You will learn in the following sections how to force line breaks with, e.g., \\\\...
Best: You will learn in the following sections how to force line breaks using, for example, the command \\\\...

**Comment by oetiker** [comment]
PRs welcome!
