### ISSUE TITLE
biblatex - Author with "and" in name

### ISSUE THREAD

**Issue by CatShootingStar** [oetiker/lshort#89]
In the subsection *More about entries* in *Bibliographies* the following example on literal ands in author names is given:
```
@book{kru,
  author = {Kruger {and} sons}
}
```
This is incorrect because **author** is a name list. This means that "Kruger and sons" would be interpreted as a personal name. The following would be correct:
```
@book{kru,
  author = {{Kruger and sons}}
}
```
See § 2.3.3 *Corporate Authors and Editors* of the biblatex package documentation.

**Comment by oetiker** [comment]
would you care to create a PR to fix this ?

**Comment by oetiker** [comment]
ping

**Comment by CatShootingStar** [comment]
*whoops*, I kinda forgot about this
