### ISSUE TITLE
French typo in §2.8.1, "élève" instead of "élv̀e"

### ISSUE THREAD

**Issue by BelugaHaechi** [oetiker/lshort#92]
In the second example box, the French word "élève" in the first row should not be "élv̀e". The corresponding code to the left should also be fixed. 
It is spelt correctly in the first box.

**Comment by oetiker** [comment]
which release are you refering to ?

**Comment by jeggao** [comment]
I believe @BelugaHaechi got the build from [https://tobi.oetiker.ch/lshort](https://tobi.oetiker.ch/lshort). The version is Nightly version 7.0.

**Comment by oetiker** [comment]
ok, version was a bit out of date ... I have synced it ... thanks for mentioning it.
